-- Supabase SQL schema for Volunteer Event app

-- 1) Users: використовуємо auth.users. Додаткові дані можна тримати в public.profiles
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  avatar_url text,
  bio text,
  city text,
  phone text,
  interests text[] default '{}',
  created_at timestamp with time zone default now()
);

-- 2) Events
create type public.event_status as enum ('upcoming','ongoing','completed','cancelled');

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null,
  start_date timestamp with time zone not null,
  end_date timestamp with time zone not null,
  location text not null,
  category text not null,
  image_url text,
  max_participants int not null default 0,
  current_participants int not null default 0,
  status public.event_status not null default 'upcoming',
  requirements text[] not null default '{}',
  organizer text not null,
  contact_info text not null,
  latitude double precision,
  longitude double precision,
  created_at timestamp with time zone default now()
);

-- 3) Favorites (wishlist)
create table if not exists public.favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  event_id uuid not null references public.events(id) on delete cascade,
  created_at timestamp with time zone default now(),
  primary key (user_id, event_id)
);

-- 4) Registrations (user -> event)
create table if not exists public.registrations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  event_id uuid not null references public.events(id) on delete cascade,
  created_at timestamp with time zone default now(),
  unique (user_id, event_id)
);

-- 5) Devices (MQTT) - опційно
create table if not exists public.devices (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete cascade,
  sensor_id text not null,
  created_at timestamp with time zone default now(),
  unique (owner_id, sensor_id)
);

-- 6) Readings (MQTT) - опційно
create table if not exists public.readings (
  id bigint generated by default as identity primary key,
  device_id uuid references public.devices(id) on delete cascade,
  value double precision not null,
  unit text default '°C',
  ts timestamp with time zone default now()
);

-- RLS
alter table public.profiles enable row level security;
alter table public.events enable row level security;
alter table public.favorites enable row level security;
alter table public.registrations enable row level security;
alter table public.devices enable row level security;
alter table public.readings enable row level security;

-- profiles: користувач бачить/оновлює свій профіль, всі можуть читати публічні дані
drop policy if exists "profiles_read_all" on public.profiles;
drop policy if exists "profiles_self_modify" on public.profiles;
drop policy if exists "profiles_self_update" on public.profiles;
drop policy if exists "profiles_auth_insert" on public.profiles;
create policy "profiles_read_all" on public.profiles
  for select using (true);
create policy "profiles_self_modify" on public.profiles
  for insert with check (auth.uid() = id);
create policy "profiles_self_update" on public.profiles
  for update using (auth.uid() = id);
-- Дозволити автентифікованим створювати профіль для себе
create policy "profiles_auth_insert" on public.profiles
  for insert with check (auth.role() = 'authenticated');

-- Автоматичне створення профілю при реєстрації користувача в auth.users
drop function if exists public.handle_new_user cascade;
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles(id, name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'full_name', new.email),
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- events: читати можуть всі, створювати/редагувати лише адміни (простий варіант: заборонити з клієнта)
drop policy if exists "events_select_all" on public.events;
create policy "events_select_all" on public.events for select using (true);

-- favorites: лише власник
drop policy if exists "favorites_owner_select" on public.favorites;
drop policy if exists "favorites_owner_ins" on public.favorites;
drop policy if exists "favorites_owner_del" on public.favorites;
create policy "favorites_owner_select" on public.favorites
  for select using (auth.uid() = user_id);
create policy "favorites_owner_ins" on public.favorites
  for insert with check (auth.uid() = user_id);
create policy "favorites_owner_del" on public.favorites
  for delete using (auth.uid() = user_id);

-- registrations: лише власник
drop policy if exists "registrations_owner_select" on public.registrations;
drop policy if exists "registrations_owner_ins" on public.registrations;
drop policy if exists "registrations_owner_del" on public.registrations;
create policy "registrations_owner_select" on public.registrations
  for select using (auth.uid() = user_id);
create policy "registrations_owner_ins" on public.registrations
  for insert with check (auth.uid() = user_id);
create policy "registrations_owner_del" on public.registrations
  for delete using (auth.uid() = user_id);

-- devices & readings: лише власник
drop policy if exists "devices_owner" on public.devices;
create policy "devices_owner" on public.devices
  for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
drop policy if exists "readings_owner" on public.readings;
create policy "readings_owner" on public.readings
  for all using (
    exists(select 1 from public.devices d where d.id = readings.device_id and d.owner_id = auth.uid())
  ) with check (
    exists(select 1 from public.devices d where d.id = readings.device_id and d.owner_id = auth.uid())
  );

-- RPC для participants
create or replace function public.increment_participants(p_event_id uuid)
returns void language sql security definer as $$
  update public.events
  set current_participants = current_participants + 1
  where id = p_event_id and current_participants < max_participants;
$$;

create or replace function public.decrement_participants(p_event_id uuid)
returns void language sql security definer as $$
  update public.events
  set current_participants = greatest(current_participants - 1, 0)
  where id = p_event_id;
$$;

-- Створення Storage bucket для аватарок
-- Це потрібно виконати вручну в Supabase Dashboard або через CLI
-- create policy "Avatar images are publicly accessible" on storage.objects for select using (bucket_id = 'avatars');
-- create policy "Users can upload their own avatar" on storage.objects for insert with check (bucket_id = 'avatars' and auth.uid()::text = (storage.foldername(name))[1]);
-- create policy "Users can update their own avatar" on storage.objects for update using (bucket_id = 'avatars' and auth.uid()::text = (storage.foldername(name))[1]);
-- create policy "Users can delete their own avatar" on storage.objects for delete using (bucket_id = 'avatars' and auth.uid()::text = (storage.foldername(name))[1]);

-- Sample seed (розкоментуйте для тестової БД)
-- insert into public.events(title, description, start_date, end_date, location, category, max_participants, organizer, contact_info, status)
-- values ('Прибирання парку', 'Допоможемо прибрати парк', now() + interval '3 day', now() + interval '3 day' + interval '3 hour', 'Парк ім. Шевченка, Львів', 'Екологія', 30, 'Зелений Львів', '+380501234567', 'upcoming');


-- RPC: агрегована статистика користувача з рівнями
create or replace function public.get_user_stats(uid uuid)
returns table (
  total_events int,
  total_hours int,
  current_streak int,
  longest_streak int,
  categories text[],
  join_date timestamptz,
  level_name text,
  level_emoji text,
  progress_to_next int,
  progress_percentage double precision
) language plpgsql security definer as $$
declare
  v_total int := 0;
  v_hours int := 0;
  v_join timestamptz := now();
  v_categories text[] := '{}';
  v_level_name text := 'Новачок';
  v_level_emoji text := '🌱';
  v_progress_to_next int := 0;
  v_progress_percentage double precision := 0;
  v_current_streak int := 0;
  v_longest_streak int := 0;
begin
  -- загальна к-сть івентів та години за тривалістю
  select
    count(*)::int,
    coalesce(sum(greatest(extract(epoch from (e.end_date - e.start_date)) / 3600, 0)), 0)::int,
    min(r.created_at)
  into v_total, v_hours, v_join
  from public.registrations r
  join public.events e on e.id = r.event_id
  where r.user_id = uid;

  -- топ категорії
  select coalesce((array_agg(cat order by cnt desc))[1:5], '{}')
  into v_categories
  from (
    select e.category as cat, count(*) as cnt
    from public.registrations r
    join public.events e on e.id = r.event_id
    where r.user_id = uid
    group by e.category
  ) t;

  -- прості рівні як у клієнта
  if v_total < 5 then
    v_level_name := 'Новачок'; v_level_emoji := '🌱'; v_progress_to_next := 5 - v_total; v_progress_percentage := v_total / 5.0;
  elsif v_total < 10 then
    v_level_name := 'Волонтер'; v_level_emoji := '🤝'; v_progress_to_next := 10 - v_total; v_progress_percentage := (v_total - 5) / 5.0;
  elsif v_total < 20 then
    v_level_name := 'Помічник'; v_level_emoji := '💪'; v_progress_to_next := 20 - v_total; v_progress_percentage := (v_total - 10) / 10.0;
  elsif v_total < 50 then
    v_level_name := 'Чемпіон'; v_level_emoji := '🏆'; v_progress_to_next := 50 - v_total; v_progress_percentage := (v_total - 20) / 30.0;
  elsif v_total < 100 then
    v_level_name := 'Герой'; v_level_emoji := '🦸'; v_progress_to_next := 100 - v_total; v_progress_percentage := (v_total - 50) / 50.0;
  else
    v_level_name := 'Легенда'; v_level_emoji := '👑'; v_progress_to_next := 0; v_progress_percentage := 1.0;
  end if;

  -- streaks (спрощено до 0; можна доробити пізніше)
  v_current_streak := 0;
  v_longest_streak := 0;

  return query select v_total, v_hours, v_current_streak, v_longest_streak, v_categories, v_join,
                       v_level_name, v_level_emoji, v_progress_to_next, v_progress_percentage;
end; $$;

